[sleek]
text               = eae1db
subtext            = d4c4b7
nav-active-text    = 482905
main               = 17130f
main-secondary     = 2e2925
sidebar            = 1f1b17
player             = 231f1b
card               = 110d0a
shadow             = 000000
selected-row       = 50453b
button             = ffe3cd
button-active      = f1bc8c
button-disabled    = 9d8e83
tab-active         = 594533
notification       = 93000a
notification-error = ffb4ab
playback-bar       = ffe3cd
play-button        = 54320d

; RGB channels for opacity mixins inside the CSS sheet
rgb-main-secondary = 46, 41, 37
rgb-sidebar        = 31, 27, 23
rgb-shadow         = 0, 0, 0
